<?php

namespace App\Enums;

enum AnomalyType: string
{
    case UNUSUAL_EXPENSE = 'UNUSUAL_EXPENSE';
    case EXPENSE_SPIKE = 'EXPENSE_SPIKE';
    case INCOME_DROP = 'INCOME_DROP';
    case NEGATIVE_CASH_FLOW = 'NEGATIVE_CASH_FLOW';
    case NEGATIVE_BALANCE = 'NEGATIVE_BALANCE';
    case REPEATED_TRANSACTION = 'REPEATED_TRANSACTION';
    case BUDGET_OVERRUN = 'BUDGET_OVERRUN';
    case OVERDUE_RECEIVABLE = 'OVERDUE_RECEIVABLE';
    case OVERDUE_DEBT = 'OVERDUE_DEBT';
    case MATERIAL_CAPITAL_PRIVE = 'MATERIAL_CAPITAL_PRIVE';
}
