<?php

namespace App\Enums;

enum AuditAction: string
{
    case CREATE = 'CREATE';
    case UPDATE = 'UPDATE';
    case DELETE = 'DELETE';
    case FINANCE_ENTITY_DELETED = 'FINANCE_ENTITY_DELETED';
    case ACTIVATE = 'ACTIVATE';
    case DEACTIVATE = 'DEACTIVATE';
    case SET_DEFAULT = 'SET_DEFAULT';
    case REVOKE = 'REVOKE';
    case REGENERATE = 'REGENERATE';
    case PAYMENT = 'PAYMENT';
    case TRANSFER = 'TRANSFER';
    case AI_CHAT_REQUESTED = 'AI_CHAT_REQUESTED';
    case ACCESS_LINK_DELETED = 'ACCESS_LINK_DELETED';
    case PLANTATION_INTEGRATION_ACTIVATED = 'PLANTATION_INTEGRATION_ACTIVATED';
    case PLANTATION_INTEGRATION_DEACTIVATED = 'PLANTATION_INTEGRATION_DEACTIVATED';
    case PLANTATION_INTEGRATION_SYNCED = 'PLANTATION_INTEGRATION_SYNCED';
    case PLANTATION_ACCESS_LINK_CREATED = 'PLANTATION_ACCESS_LINK_CREATED';
    case PLANTATION_ACCESS_LINK_REVOKED = 'PLANTATION_ACCESS_LINK_REVOKED';
    case PLANTATION_ACCESS_LINK_ACTIVATED = 'PLANTATION_ACCESS_LINK_ACTIVATED';
    case PLANTATION_ACCESS_LINK_REGENERATED = 'PLANTATION_ACCESS_LINK_REGENERATED';
    case PLANTATION_ACCESS_LINK_DELETED = 'PLANTATION_ACCESS_LINK_DELETED';
    case PLANTATION_OPERATING_BUDGET_CREATED = 'PLANTATION_OPERATING_BUDGET_CREATED';
    case PLANTATION_OPERATING_BUDGET_UPDATED = 'PLANTATION_OPERATING_BUDGET_UPDATED';
    case PLANTATION_OPERATING_BUDGET_SYNCED = 'PLANTATION_OPERATING_BUDGET_SYNCED';
    case PLANTATION_EVENT_PROCESSED = 'PLANTATION_EVENT_PROCESSED';
    case PLANTATION_EVENT_CONFLICT = 'PLANTATION_EVENT_CONFLICT';

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }

    public static function isValid(?string $value): bool
    {
        return $value !== null && self::tryFrom($value) !== null;
    }
}
